# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signal_layout.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 904)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(196, 143, 711, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setStyleSheet("background-color : grey;")
        self.label_13.setLineWidth(0)
        self.label_13.setText("")
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setStyleSheet("background-color : red;")
        self.label_15.setText("")
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_36.setText("")
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_53.setText("")
        self.label_53.setScaledContents(True)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 5, 4, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_54.setText("")
        self.label_54.setScaledContents(True)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 5, 5, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_55.setText("")
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 4, 5, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_56.setText("")
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 4, 4, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_57.setText("")
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 5, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_58.setText("")
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 4, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_59.setText("")
        self.label_59.setScaledContents(True)
        self.label_59.setObjectName("label_59")
        self.gridLayout.addWidget(self.label_59, 4, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_60.setText("")
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 5, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_61.setText("")
        self.label_61.setScaledContents(True)
        self.label_61.setObjectName("label_61")
        self.gridLayout.addWidget(self.label_61, 1, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_62.setText("")
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName("label_62")
        self.gridLayout.addWidget(self.label_62, 1, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_63.setText("")
        self.label_63.setScaledContents(True)
        self.label_63.setObjectName("label_63")
        self.gridLayout.addWidget(self.label_63, 1, 4, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_64.setText("")
        self.label_64.setScaledContents(True)
        self.label_64.setObjectName("label_64")
        self.gridLayout.addWidget(self.label_64, 1, 5, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_65.setText("")
        self.label_65.setScaledContents(True)
        self.label_65.setObjectName("label_65")
        self.gridLayout.addWidget(self.label_65, 0, 5, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_66.setText("")
        self.label_66.setScaledContents(True)
        self.label_66.setObjectName("label_66")
        self.gridLayout.addWidget(self.label_66, 0, 4, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setStyleSheet("background-color : rgb(85, 255, 127);")
        self.label_67.setText("")
        self.label_67.setScaledContents(True)
        self.label_67.setObjectName("label_67")
        self.gridLayout.addWidget(self.label_67, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setStyleSheet("background-color : grey;")
        self.label_14.setLineWidth(0)
        self.label_14.setText("")
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setStyleSheet("background-color : grey;")
        self.label_17.setLineWidth(0)
        self.label_17.setText("")
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setStyleSheet("background-color : grey;")
        self.label_18.setLineWidth(0)
        self.label_18.setText("")
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setStyleSheet("background-color : grey;")
        self.label_19.setLineWidth(0)
        self.label_19.setText("")
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setStyleSheet("background-color : grey;")
        self.label_20.setLineWidth(0)
        self.label_20.setText("")
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setStyleSheet("background-color : grey;")
        self.label_23.setLineWidth(0)
        self.label_23.setText("")
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 5, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setStyleSheet("background-color : grey;")
        self.label_24.setLineWidth(0)
        self.label_24.setText("")
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 2, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setStyleSheet("background-color : grey;")
        self.label_25.setLineWidth(0)
        self.label_25.setText("")
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 2, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setStyleSheet("background-color : grey;")
        self.label_26.setLineWidth(0)
        self.label_26.setText("")
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setStyleSheet("background-color : grey;")
        self.label_27.setLineWidth(0)
        self.label_27.setText("")
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setStyleSheet("background-color : grey;")
        self.label_28.setLineWidth(0)
        self.label_28.setText("")
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setStyleSheet("background-color : grey;")
        self.label_29.setLineWidth(0)
        self.label_29.setText("")
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setStyleSheet("background-color : grey;")
        self.label_30.setLineWidth(0)
        self.label_30.setText("")
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setStyleSheet("background-color : grey;")
        self.label_31.setLineWidth(0)
        self.label_31.setText("")
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 3, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setStyleSheet("background-color : grey;")
        self.label_32.setLineWidth(0)
        self.label_32.setText("")
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setStyleSheet("background-color : red;")
        self.label_22.setText("")
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setAutoFillBackground(False)
        self.label_21.setStyleSheet("background-color : red;")
        self.label_21.setText("")
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 3, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("background-color : red;")
        self.label_16.setText("")
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(630, 790, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("../images/maruti.jpg"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(570, 790, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("../images/maruti.jpg"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(1020, 390, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("../images/maruti.jpg"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(1020, 330, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("../images/maruti.jpg"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(450, 20, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap("../images/maruti.jpg"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(510, 20, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("../images/maruti.jpg"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(40, 480, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("../images/maruti.jpg"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(40, 420, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("../images/maruti.jpg"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(570, 760, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("../images/straight.png"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(630, 760, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("../images/right_arrow.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(450, 50, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("../images/right_arrow_3.png"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(510, 50, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("../images/straight_3.png"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(990, 390, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap("../images/straight_4.png"))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(990, 330, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("../images/right_arrow_4.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(70, 420, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap("../images/straight_2.png"))
        self.label_51.setScaledContents(True)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(70, 480, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_52.setText("")
        self.label_52.setPixmap(QtGui.QPixmap("../images/right_arrow_2.png"))
        self.label_52.setScaledContents(True)
        self.label_52.setObjectName("label_52")
        self.l1_right_turn = QtWidgets.QWidget(self.centralwidget)
        self.l1_right_turn.setGeometry(QtCore.QRect(630, 760, 31, 61))
        self.l1_right_turn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l1_right_turn.setObjectName("l1_right_turn")
        self.l1_straight = QtWidgets.QWidget(self.centralwidget)
        self.l1_straight.setGeometry(QtCore.QRect(570, 760, 31, 61))
        self.l1_straight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l1_straight.setObjectName("l1_straight")
        self.l3_right_turn = QtWidgets.QWidget(self.centralwidget)
        self.l3_right_turn.setGeometry(QtCore.QRect(450, 20, 31, 61))
        self.l3_right_turn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l3_right_turn.setObjectName("l3_right_turn")
        self.l3_straight = QtWidgets.QWidget(self.centralwidget)
        self.l3_straight.setGeometry(QtCore.QRect(510, 20, 31, 61))
        self.l3_straight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l3_straight.setObjectName("l3_straight")
        self.l4_right_turn = QtWidgets.QWidget(self.centralwidget)
        self.l4_right_turn.setGeometry(QtCore.QRect(39, 479, 61, 31))
        self.l4_right_turn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l4_right_turn.setObjectName("l4_right_turn")
        self.l4_straight = QtWidgets.QWidget(self.centralwidget)
        self.l4_straight.setGeometry(QtCore.QRect(40, 420, 61, 31))
        self.l4_straight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l4_straight.setObjectName("l4_straight")
        self.l2_right_turn = QtWidgets.QWidget(self.centralwidget)
        self.l2_right_turn.setGeometry(QtCore.QRect(991, 331, 61, 31))
        self.l2_right_turn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l2_right_turn.setObjectName("l2_right_turn")
        self.l2_straight = QtWidgets.QWidget(self.centralwidget)
        self.l2_straight.setGeometry(QtCore.QRect(990, 390, 61, 31))
        self.l2_straight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l2_straight.setObjectName("l2_straight")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(580, 710, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(910, 360, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(460, 90, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(110, 450, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l4.setFont(font)
        self.l4.setAlignment(QtCore.Qt.AlignCenter)
        self.l4.setObjectName("l4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAuthors = QtWidgets.QMenu(self.menuAbout)
        self.menuAuthors.setObjectName("menuAuthors")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBharath = QtWidgets.QAction(MainWindow)
        self.actionBharath.setObjectName("actionBharath")
        self.actionPranit = QtWidgets.QAction(MainWindow)
        self.actionPranit.setObjectName("actionPranit")
        self.actionShweta = QtWidgets.QAction(MainWindow)
        self.actionShweta.setObjectName("actionShweta")
        self.menuAuthors.addAction(self.actionBharath)
        self.menuAuthors.addAction(self.actionPranit)
        self.menuAuthors.addAction(self.actionShweta)
        self.menuAbout.addAction(self.menuAuthors.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traffic Signal Controller"))
        self.l1.setText(_translate("MainWindow", "L1"))
        self.l2.setText(_translate("MainWindow", "L2"))
        self.l3.setText(_translate("MainWindow", "L3"))
        self.l4.setText(_translate("MainWindow", "L4"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuAuthors.setTitle(_translate("MainWindow", "Authors"))
        self.actionBharath.setText(_translate("MainWindow", "Bharath"))
        self.actionPranit.setText(_translate("MainWindow", "Pranit"))
        self.actionShweta.setText(_translate("MainWindow", "Shweta"))

